from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class Priority(str, Enum):
    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    URGENT = "urgent"


class ActionIntent(str, Enum):
    ROUTE_MESSAGE = "route_message"
    PROPOSE_PLAN = "propose_plan"
    RESCHEDULE_EVENT = "reschedule_event"
    DELEGATE_TASK = "delegate_task"
    ASK_CLARIFICATION = "ask_clarification"
    FINALIZE_ITINERARY = "finalize_itinerary"


# Intents that meaningfully end the agent's involvement with the queue.
TERMINAL_INTENTS = {ActionIntent.FINALIZE_ITINERARY}


class Owner(str, Enum):
    SELF = "self"
    WORK = "work"
    FAMILY = "family"
    TRAVEL = "travel"
    FINANCE = "finance"
    LEGAL = "legal"


class ConflictExpectation(BaseModel):
    intent: ActionIntent
    owner: Owner
    priority: Priority
    require_slot: bool = False
    expected_slot_hint: str = ""
    block_if_missing_context: bool = False
    required_keywords: List[str] = Field(default_factory=list)


class CalendarEvent(BaseModel):
    """A scheduled event the agent's actions can mutate."""

    event_id: str
    title: str
    start: str = Field(default="", description="HH:MM start time, may be empty for non-time events")
    end: str = Field(default="", description="HH:MM end time")
    owner: Owner = Owner.SELF
    locked: bool = Field(default=False, description="True for mandatory events that cannot be moved")


class ClarificationSpec(BaseModel):
    """Describes information that becomes available only after the agent asks."""

    hidden_info: str = Field(..., description="Information withheld until the agent asks")
    revealed_summary_suffix: str = Field(
        default="",
        description="Text appended to the conflict summary after the reveal",
    )
    post_reveal_expected: Optional[ConflictExpectation] = Field(
        default=None,
        description="Expected action AFTER the clarification is revealed; None means use base expectation",
    )


class CascadeRule(BaseModel):
    """Describes a follow-on conflict that may be generated by the agent's action."""

    trigger_intent: ActionIntent = Field(..., description="Which intent triggers the cascade check")
    trigger_slot_after_minutes: Optional[int] = Field(
        default=None,
        description="If proposed_slot resolves to >= this many minutes (24h clock), trigger",
    )
    trigger_owner: Optional[Owner] = Field(
        default=None,
        description="Optionally require a specific owner to trigger",
    )
    follow_on_id_prefix: str = Field(default="C", description="Prefix for the generated cascade conflict id")
    follow_on_source: str = Field(default="cascade", description="Source label for the generated conflict")
    follow_on_summary: str = Field(..., description="Summary text for the generated conflict")
    follow_on_constraints: List[str] = Field(default_factory=list)
    follow_on_expected: ConflictExpectation = Field(..., description="Expected action for the generated conflict")


class PendingClarification(BaseModel):
    """A queued info reveal that becomes visible at a future step."""

    conflict_id: str
    reveal_at_step: int = Field(..., description="Step index at which the revelation becomes visible")
    revealed_summary_suffix: str
    post_reveal_expected: Optional[ConflictExpectation] = None


class ConflictCase(BaseModel):
    """A single conflict the agent must resolve.

    Backwards-compatible: only `conflict_id`, `source`, `summary`, `constraints`, and
    `expected` are required. The new fields support procedural generation.
    """

    conflict_id: str
    source: str
    summary: str
    constraints: List[str] = Field(default_factory=list)
    expected: ConflictExpectation
    clarification: Optional[ClarificationSpec] = Field(
        default=None,
        description="If set, this conflict has hidden info revealed via ask_clarification",
    )
    cascade_rule: Optional[CascadeRule] = Field(
        default=None,
        description="If set, an agent action satisfying the rule generates a follow-on conflict",
    )
    is_cascade: bool = Field(default=False, description="True if this conflict was generated mid-episode")
    revealed_info: Optional[str] = Field(
        default=None,
        description="Set on observation when clarification has been revealed for this conflict",
    )


class TaskDefinition(BaseModel):
    id: str
    title: str
    difficulty: str
    description: str
    max_steps: int
    conflicts: List[ConflictCase]
    initial_calendar: List[CalendarEvent] = Field(
        default_factory=list,
        description="Calendar state at episode start. Mutated by the env on reschedule_event.",
    )


class ConflictDecision(BaseModel):
    conflict_id: str
    intent: ActionIntent
    owner: Owner
    priority: Priority
    proposed_slot: str = ""
    needs_clarification: bool = False
    message_template: str = ""


class ConflictAction(BaseModel):
    intent: ActionIntent
    owner: Owner
    priority: Priority
    proposed_slot: str = Field(default="", max_length=80)
    needs_clarification: bool = False
    message_template: str = Field(default="", max_length=500)

    @field_validator("proposed_slot", mode="before")
    @classmethod
    def normalize_slot(cls, value: Any) -> str:
        if value is None:
            return ""
        return str(value).strip()

    @field_validator("message_template", mode="before")
    @classmethod
    def normalize_template(cls, value: Any) -> str:
        if value is None:
            return ""
        return str(value).strip()


class WorldState(BaseModel):
    """Mutable world state that persists across steps within an episode."""

    calendar: List[CalendarEvent] = Field(default_factory=list)
    pending_clarifications: List[PendingClarification] = Field(default_factory=list)
    revealed_info: Dict[str, str] = Field(
        default_factory=dict,
        description="conflict_id -> revealed text, populated when a clarification reveals info",
    )
    cascade_queue: List[ConflictCase] = Field(
        default_factory=list,
        description="Conflicts dynamically appended by cascade rules during the episode",
    )
    cascade_count: int = Field(default=0, description="Total cascades generated this episode")


class ConflictObservation(BaseModel):
    model_config = ConfigDict(extra="allow")

    task_id: str
    task_difficulty: str
    step_index: int
    max_steps: int
    processed_count: int
    remaining_count: int
    current_conflict: Optional[ConflictCase] = None
    history: List[ConflictDecision] = Field(default_factory=list)
    open_risks: List[str] = Field(default_factory=list)
    last_feedback: str = ""
    available_calendar: List[CalendarEvent] = Field(
        default_factory=list,
        description="Snapshot of the calendar visible to the agent",
    )
    pending_clarifications: List[PendingClarification] = Field(
        default_factory=list,
        description="Outstanding clarifications the agent has asked for",
    )
    cascade_count: int = Field(default=0, description="Number of cascade conflicts spawned so far")


class ConflictReward(BaseModel):
    score: float = Field(ge=0.0, le=1.0)
    components: Dict[str, float] = Field(default_factory=dict)
    penalties: Dict[str, float] = Field(default_factory=dict)


class ConflictState(BaseModel):
    task_id: str
    task_difficulty: str
    step_index: int
    max_steps: int
    done: bool
    cumulative_reward: float = 0.0
    average_step_score: float = 0.0
    final_score: float = 0.0
    decisions: List[ConflictDecision] = Field(default_factory=list)
    score_history: List[float] = Field(default_factory=list)
    reward_history: List[float] = Field(default_factory=list)
    clarification_requests: int = 0
    last_action_error: Optional[str] = None
    world: WorldState = Field(default_factory=WorldState)


class ConflictStepResult(BaseModel):
    observation: ConflictObservation
    reward: float = Field(ge=0.0, le=1.0)
    done: bool
    info: Dict[str, Any] = Field(default_factory=dict)
